repos:
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: env/bin/flake8
        language: python
        types: [python]
        exclude: reader/postgres_decoder.py
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: env/bin/pytest
        language: python
        types: [python]
        pass_filenames: false
